### ISSUE TITLE
Error using tinderauth command line

### ISSUE THREAD

**Issue by tr00p3r** [tinderjs/tinderauth#6]
Getting your tinder fb access token this can take a while... (1-3 min)
<![EX[["CSS timeout [%s] at %s | concurrency: %s","P/mr5","https://static.xx.fbcdn.net/rsrc.php/v3/y-/r/Gqca1raWXAL.css","1"]]]>
    at Object.j (https://static.xx.fbcdn.net/rsrc.php/v3/yJ/r/FMk5jMoG8i6.js:66:358)
    at Array.<anonymous> (https://static.xx.fbcdn.net/rsrc.php/v3/yJ/r/FMk5jMoG8i6.js:79:2469)
    at q (https://static.xx.fbcdn.net/rsrc.php/v3/yJ/r/FMk5jMoG8i6.js:65:838)
    at Window.aa (https://static.xx.fbcdn.net/rsrc.php/v3/yJ/r/FMk5jMoG8i6.js:65:1135)
    at Object.ba  (https://static.xx.fbcdn.net/rsrc.php/v3/yJ/r/FMk5jMoG8i6.js:41:1608)
    at Window.ga (https://static.xx.fbcdn.net/rsrc.php/v3/yJ/r/FMk5jMoG8i6.js:62:3125)
    at Window.window._evaluate (C:\Users\mail\AppData\Roaming\npm\node_modules\tinderauth\node_modules\zombie\lib\document.js:253:155)
    at C:\Users\mail\AppData\Roaming\npm\node_modules\tinderauth\node_modules\zombie\lib\eventloop.js:153:36
    at Immediate._onImmediate (C:\Users\mail\AppData\Roaming\npm\node_modules\tinderauth\node_modules\zombie\lib\eventloop.js:676:13)
    at processImmediate  (timers.js:383:17)
Original error: JSLog.warn: <![EX[["CSS timeout [%s] at %s | concurrency: %s","P/mr5","https://static.xx.fbcdn.net/rsrc.php/v3/y-/r/Gqca1raWXAL.css","1"]]]>

**Comment by tr00p3r** [comment]
Guessing this is due to the extra authentication requirements on my account

**Comment by tr00p3r** [comment]
Ok, nope, wasn't that.
